apps/order/urls.py
from django.urls import include, path, re_path
from apps.order import views
from django.views.generic import TemplateView

app_name = 'orders'


urlpatterns = [
   path('', views.OrderViewSet.as_view({'get':'data'}), name='order'),
   re_path(
      r"^(?P<delivery>newpost|curier)/",
      views.OrderViewSet.as_view({'get':'data', 'post':'data'}), 
      name='order'
   ),
   re_path(
      r"^api/(?P<delivery>newpost|curier)/",
      views.OrderViewSet.as_view({'post':'api'}), 
      name='order_api'
   ),
   path('create/',          views.CreateOrderView.as_view(), name='create'),
   path('payment/',         views.OrderPay.as_view(),    name='payment'),
   path('prepayment/',      views.OrderPrePay.as_view(),    name='prepayment'),
   path('repeat/<id>/',     views.OrderRepeat.as_view(), name="repeat"),
   path('success/',         views.order_success,         name='success'),
   path('payment_response', views.payment_response,      name="payment_response"),
   path('apply_promo', views.views__promocode.apply_promo, name="apply_promo"),

]

apps/user/urls.py
from django.urls import path, re_path, include
from django.contrib.auth import views as authViews
from django.views.generic import TemplateView
from apps.user.forms import PasswordRestoreForm
from . import views

app_name = 'user'


profile = [
    path('',                 views.user_data,            name='profile'),
    path('orders/',          views.user_orders,          name='user_orders'),
    path('wishlist/',        views.user_wishlist,        name='user_wishlist'),
    path('company/',         views.user_company,         name='user_company'),
    path('comments/',        views.user_comments,        name='user_comments'),
    path('questions/',       views.user_questions,       name='user_questions'),
    path('logout/',          views.user_logout,          name='user_logout'),
    path('password_change/', views.user_password_change, name='user_password_change'),
    
]


registration = [
    path('',                   views.CustomerRegistration.as_view(), name='registration'),
    path('business/',          views.PartnerRegistration.as_view(),  name='registration_business'),
    path('success/',           TemplateView.as_view(template_name="user/registration/customer/success.html"), name='registration_success'),
    path('business/success/',  TemplateView.as_view(template_name="user/registration/partner/success.html"),  name='registration_business_success'),
]


pssword_restore = [
    path(
        'html/', TemplateView.as_view(
            template_name = 'user/password_restore/email_template.html',
        ), 
        kwargs={'uidb64' : '123123', 'token' : '1232'},
        name='restore_password__success',
    ),
   
    path(
        '',                        
        authViews.PasswordResetView.as_view(
            form_class =    PasswordRestoreForm,
            template_name = 'user/password_restore/form.html',
            from_email =    'office.fortisbeauty@gmail.com',
            success_url =   '/restore_password/success/',
        ), 
        name='restore_password'
    ),
    path(
        'success/',                
        TemplateView.as_view(
            template_name = 'user/password_restore/success.html'
        ), 
        name='restore_password__success'
    ),
    path(
        'done/', 
        authViews.PasswordResetDoneView.as_view(), 
        kwargs={'template_name': 'user/password_restore/done.html'}, 
        name='restore_password__done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        authViews.PasswordResetConfirmView.as_view(
            template_name = 'user/password_restore/link_form.html',
            success_url =   '/login',
        ),
        name='restore_password__confirm'
    ),
]


urlpatterns = [
    path('login/',   views.LoginView.as_view(),  name='login'),
    path('logout/',  views.user_logout,          name='logout'),
    path('profile/',           include(profile)),
    path('restore_password/',  include(pssword_restore)),
    path('registration/',      include(registration)),
    path('activate/<uidb64>/<token>/',views.activate, name='activate'),  
]

project/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, re_path
from django.conf.urls.i18n import i18n_patterns
from django.urls import reverse
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve


urlpatterns = []

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()
  


urlpatterns += i18n_patterns(
    path('',          include('apps.user.urls',      namespace='user')),
    path('blog/',     include('apps.blog.urls',      namespace='blog')),
    path('order/',    include('apps.order.urls',     namespace='order')),
    path('core/',     include('apps.core.urls',      namespace='core')),
    path('search/',   include('apps.search.urls',    namespace='search')),
    path('wishlist/', include('apps.wishlist.urls',  namespace='wishlist')),
    path('opt/',      include('apps.opt.urls',       namespace='opt')),
    path('i18n/',     include('django.conf.urls.i18n')),
    path('admin/clearcache/', include('clearcache.urls')),
    path('admin/',  admin.site.urls),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    
    # path('jet/',    include('jet.urls', 'jet')),
    # path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('1c/',     include('apps.sync1c.urls',  namespace='sync1c')),
    path('',        include('apps.shop.urls',   namespace='shop')),
    path('',        include('apps.pages.urls',  namespace='pages')),
    prefix_default_language=False
)

apps/user/forms/forms__password.py
from django import forms
from django.contrib.auth.forms import PasswordResetForm
from django.utils.translation import ugettext, ugettext_lazy as _
from django.template.loader import render_to_string 
from apps.user.models import CustomUser
from django.core.mail import send_mail






class PasswordRestoreForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super(PasswordRestoreForm, self).__init__(*args, **kwargs)
        self.fields['email'].label = ''
        self.fields['email'].required = True
        self.fields['email'].widget.attrs['data-type'] =   'email'
        self.fields['email'].widget.attrs['data-empty'] =  'Введите Ваш Email'
        self.fields['email'].widget.attrs['data-error'] =  'Email имеет не верный формат'
        self.fields['email'].widget.attrs['placeholder'] = 'Email *'


    def clean(self):
        cd = super().clean()
        email = cd['email']
        user = CustomUser.objects.filter(email=email).first()
        if user == None:
            raise forms.ValidationError([f"Пользователь с email: {email} не зарегестрирован в системе"])

    
    def send_mail(self, subject_template_name, email_template_name, context, from_email, to_email, html_email_template_name=None):
        cd = super().clean()
        message = render_to_string('user/password_restore/email_template.html', context=context)
        send_mail(
            subject = _('Востанволение пароля'),
            from_email = "office.fortisbeauty@gmail.com",
            recipient_list = [cd['email']],
            message = message,
            html_message = message,
            fail_silently = True,
        )

apps/user/forms/forms__profile.py
from django import forms
from apps.user.models import CustomUser


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['email','phone','first_name','last_name','father_name','city']

    def __init__(self, language='ru', *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        # EMAIL
        self.fields['email'].label = ''
        self.fields['email'].required = True
        self.fields['email'].widget.attrs['data-type'] =   'text'
        self.fields['email'].widget.attrs['data-empty'] =  'Введите Ваш Email'
        self.fields['email'].widget.attrs['data-error'] =  'Email имеет не верный формат'
        self.fields['email'].widget.attrs['placeholder'] = 'Email *'
        # PHONE
        self.fields['phone'].label = ''
        self.fields['phone'].required = True
        self.fields['phone'].widget.attrs['data-type'] =   'text'
        self.fields['phone'].widget.attrs['data-empty'] =  'Введите Номер телефона'
        self.fields['phone'].widget.attrs['placeholder'] = 'Номер телефона *'
        # FIRST NAME
        self.fields['first_name'].label = ''
        self.fields['first_name'].required = True
        self.fields['first_name'].widget.attrs['data-type'] =   'text'
        self.fields['first_name'].widget.attrs['data-empty'] =  'Введите Ваше имя'
        self.fields['first_name'].widget.attrs['placeholder'] = 'Имя *'
        # LAST NAME
        self.fields['last_name'].label = ''
        self.fields['last_name'].required = True
        self.fields['last_name'].widget.attrs['data-type'] =   'text'
        self.fields['last_name'].widget.attrs['data-empty'] =  'Введите Вашу фамилию'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Фамилия *'
        # FATHER NAME
        self.fields['father_name'].label = ''
        self.fields['father_name'].required = True
        self.fields['father_name'].widget.attrs['data-type'] =   'text'
        self.fields['father_name'].widget.attrs['data-empty'] =  'Введите Ваше отчество'
        self.fields['father_name'].widget.attrs['placeholder'] = 'Отчество *'
        # CITY
        self.fields['city'].label = ''
        self.fields['city'].required = True
        self.fields['city'].widget.attrs['data-type'] =   'text'
        self.fields['city'].widget.attrs['data-empty'] =  'Ваш город для доставки'
        self.fields['city'].widget.attrs['placeholder'] = 'Город *'

      

apps/user/views/views__authenticate.py
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import render, redirect
from apps.user.forms import LoginForm
from django.views import View



class LoginView(View):
    form_class = LoginForm
    template_name = 'user/login.html'

    def get(self, request):
        if request.user.is_authenticated:
            return redirect('user:profile')
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        if request.user.is_authenticated:
            return redirect('user:profile')
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data['username'], password=form.cleaned_data['password']
            )
            if user:
                login(request, user)
                if request.META.get('HTTP_REFERER'):
                    return redirect(request.META.get('HTTP_REFERER'))
                if request.GET.get('next'):
                    return redirect(request.GET.get('next'))
                if request.GET.get('redirect'):
                    return redirect(request.GET.get('redirect'))
                return redirect('/')
        return render(request, self.template_name, {'form': form})



def user_logout(request):
    logout(request)
    return redirect('/')










apps/user/views/views__contacts.py
from django import forms
from django.http import JsonResponse
from django.views.decorators.http import require_http_methods
from apps.user.models import CustomUser
import json



@require_http_methods(["POST"])
def user_subscribe(request):
    args = {}
    data = json.loads(request.body.decode('utf-8'))
    # GET OR CREATE USER
    try:    
        user = CustomUser.objects.get(**{ user_data['field'] : user_data['username'] })
        user.subscribed = True
        user.save()
    except: 
        user = CustomUser.objects.create_user(username=user_data['username'], data=data)

    msg = 'Спасибо что проявили интерес к нашим новостям. Подписка оформлена. Email: %s' % user.email

    response =  json.dumps({'status' : msg}, ensure_ascii=False).encode('utf8')
    return JsonResponse(json.loads(response.decode('utf8')))



apps/user/views/views__password_restore.py
from django.contrib.auth import views as auth_views
from apps.user.forms import PasswordRestoreForm


class RestorePasswordFormView(auth_views.PasswordResetView):
    form_class = PasswordRestoreForm
    from_email = 'office.fortisbeauty@gmail.com'
    template_name = 'user/password_restore/form.html'
    email_template_name = 'user/password_restore/email_template.html',
    html_email_template_name = 'user/password_restore/email_template.html',
    success_url = '/restore_password/success/'

apps/user/views/views__profile.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import logout
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from apps.user.forms.forms__user_data import *
from apps.order.models import Order
from apps.order.serializers import OrderSerializer
from apps.shop.models import Comment


@login_required()
def user_data(request):
    context = {}
    user=request.user
    forms = {
        'main' :           UserDataMainForm, 
        'contacts' :       UserDataConstactsForm,
        'adress_chosen' :  UserAdressChosenFormSetFactory,
        'adress' :         UserAdressFromSet,
    }

    if request.method == 'POST':
        key = request.GET.get('form')
        if key in forms.keys():
            form = forms[key](data=request.POST, instance=user)
            if form.is_valid():
                form.save()

    for key in forms.keys():
        form = forms[key]
        forms[key] = form(instance=user)
            
    context['forms'] = forms
    return render(request, 'user/profile/profile__userdata.html', context)


@login_required()
def user_orders(request):
    orders = OrderSerializer(
        Order.objects.filter(user=request.user), many=True
    ).data
    return render(request, 'user/profile/profile__orders.html', {'orders' : orders})


@login_required()
def user_wishlist(request):
    return render(request, 'user/profile/profile__wishlist.html')


@login_required()
def user_company(request):
   
    if request.method == 'POST':
        # Company form
        if request.GET.get('real_price'):
            # See real prices
            real_price_form = UserRealPrice(data=request.POST, instance=request.user)
            if real_price_form.is_valid():
                real_price_form.save()
        else:
            formset = UserCompanyFormSet(data=request.POST, instance=request.user)
            if formset.is_valid():
                formset.save()
        
    
    # Company form
    formset = UserCompanyFormSet(instance=request.user)
        # See real prices
    real_price_form = UserRealPrice(instance=request.user)

    return render(request, 'user/profile/profile__company.html', {
        'formset' : formset,
        'real_price_form' : real_price_form

    })


@login_required()
def user_password_change(request):
    done = False
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            return redirect(reverse('user:user_password_change'))
    else:
        form = PasswordChangeForm(user = request.user)
    return render(request, 'user/profile/profile__passwordchange.html', {'form':form, 'done' : done})


@login_required()
def user_logout(request):
    logout(request)
    return redirect('/')


@login_required()
def user_comments(request):
    comments = Comment.objects.filter(user=request.user, type="COMMENT")
    return render(request, 'user/profile/profile__comments.html', {
        'comments': comments
    })

@login_required()
def user_questions(request):
    comments = Comment.objects.filter(user=request.user, type="QUESTION")
    return render(request, 'user/profile/profile__questions.html', {
        'comments': comments
    })

templates/user/profile/profile.html
{% extends 'base.html' %}
{% load static %}

{% block links %}
    <link rel="stylesheet" href="{% static 'css/user/profile/profile.css' %}">
    <link rel="stylesheet" href="{% static 'css/user/profile/profile__navigation.css' %}">
    <link rel="stylesheet" href="{% static 'css/user/profile/profile__orders.css' %}">
    <link rel="stylesheet" href="{% static 'css/user/profile/from.css' %}">
    <link rel="stylesheet" href="{% static 'css/shop/product/product__comments.css' %}">
    
{% endblock %}

{% block content %}
    <div class="content">
        <div class="breadcrumbs">
            <a href="/">
                <span>Головна</span>
            </a>
            <span class="slash">/</span>
            <span>Кабінет користувача</sapn>
        </div>    
    </div>
    <div class="content">
        <div class="profile">
        <div>
            <ul class="navigation">
                <a href="{% url 'user:profile' %}">
                  <li>
                      <img src="{% static 'img/icons/svg/Avatar.svg' %}" alt="*">
                      <p>
                          <span>Особиста інформація</span>
                          <span class="email">{{ request.user.email }}</span>
                      </p>
                    </li>
                </a>
                <a href="{% url 'user:user_orders' %}">
                    <li>
                      <img src="{% static 'img/icons/svg/Basket.svg' %}" alt="*">
                      <p>Мої замовлення</p>
                    </li>
                </a>
                <a href="{% url 'user:user_wishlist' %}">
                    <li>
                        <img src="{% static 'img/icons/svg/Heart.svg' %}" alt="*">
                        <p>Список бажань</p>
                    </li>
                </a>
                {% if request.user.is_whoosaler %}
                <a href="{% url 'user:user_company' %}">
                    <li>
                        <img src="{% static 'img/icons/svg/Page.svg' %}" alt="*">
                        <p>Інформація про компанію</p>
                    </li>
                </a>
                {% endif %}
                <a href="{% url 'user:user_comments' %}">
                  <li>
                      <img src="{% static 'img/icons/svg/Comment.svg' %}" alt="*">
                      <p>Мої відгуки</p>
                    </li>
                </a>
                <a href="{% url 'user:user_questions' %}">
                    <li>
                        <img src="{% static 'img/icons/svg/Comment.svg' %}" alt="*">
                        <p>Мої питання</p>
                      </li>
                  </a>
                <a href="{% url 'user:user_logout' %}">
                    <li>
                        <img src="{% static 'img/icons/svg/Forward_2.svg' %}" alt="*">
                        <p>Вийти</p>
                    </li>
                </a>
            </ul>
        </div>
        <div class="data profile_data">
            {% with user=request.user %}
                {% block profile %}{% endblock %}
            {% endwith %}
        </div>
    </div>
</div>
    

{% endblock %}

{% block js %}
<script>
    const profileData = document.querySelector('.profile_data') 
    var profileDataInputs = profileData.querySelectorAll('input, select, input:not(.edit)')
    var edits = profileData.querySelectorAll('input.edit')

    for (let input of profileDataInputs) {
        input.dataset.value = input.value
    }

    for (let edit of edits) {
        edit.onchange = () => {
            if (edit.checked == false) {
               let form = edit.parentElement.querySelector('.form')
               for (let input of form.querySelectorAll('input, select')) {
                    input.value = input.dataset.value
                    
               }
            }
        }
    }
</script>
{% endblock %}

templates/user/profile/profile__comments.html
{% extends './profile.html' %}
{% load static %}


{% block profile %}
<div class="user__comments reviews">
    <p class="title1">Мої відгуки</p>
    <ul class="product_reviews">
        {% include 'shop/product/comments/comments__list.html' with comment_product=True %}
    </ul>
</div>
{% endblock %}

templates/user/profile/profile__company.html
{% extends './profile.html' %}
{% load static %}
{% block profile %}

<div class="company__info forms">
    <p class="title1">Інформація про компанію</p>
    <ul>
        <!-- Realprice -->
        <li class="block user__company-info">
            <input class="edit" type="checkbox" id="user__company-info_edit">
            <div class="heading">
                <p class="title2">Хочу купувати за рекламним прайсом</p>
                <label for="user__company-info_edit">
                    <img src="{% static 'img/icons/edit.png' %}" alt="">
                    <span class="unchecked">Редагувати</span>
                    <span class="checked">Відмінити</span>
                </label>
            </div>
            <form action="{% url 'user:user_company' %}?real_price=change" method="POST" class="form">
                {% csrf_token %}
             
                <div class="hidden">
                    {% for field in real_price_form.hidden_fields %}
                        {{ field }}
                    {% endfor %}
                </div>
                <div class="fields">
                    {% for field in real_price_form.visible_fields %}
                        <div class="{{ field.name }}">
                            {{ field.label_tag }}
                            {{ field.errors }}
                            <p>{{ field }}</p>
                        </div>
                    {% endfor %}
                </div>
               
                <button type="submit">Обновити</button>
            </form>
        </li>

        <!-- Company -->
        <li class="block user__company-info">
            <input class="edit" type="checkbox" id="user__company-info_edit">
            <div class="heading">
                <p class="title2">Компанія</p>
                <label for="user__company-info_edit">
                    <img src="{% static 'img/icons/edit.png' %}" alt="">
                    <span class="unchecked">Редагувати</span>
                    <span class="checked">Відмінити</span>
                </label>
            </div>
            <form action="{% url 'user:user_company' %}" method="POST" class="form">
                {% csrf_token %}
                {{ formset.management_form }}
                {% for f in formset %}
                <div class="hidden">
                    {% for field in f.hidden_fields %}
                        {{ field }}
                    {% endfor %}
                </div>
                <div class="fields">
                    {% for field in f.visible_fields %}
                        <div class="{{ field.name }}">
                            {{ field.label_tag }}
                            {{ field.errors }}
                            {% if field.name == 'business_type' %}
                                {{ field }}
                            {% else %}
                                <p>{{ field }}</p>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
                {% endfor %}
                <button type="submit">Обновити</button>
            </form>
        </li>
    </ul>
</div>
{% endblock %}

templates/user/profile/profile__orders.html
{% extends './profile.html' %}
{% load static %}
{% block profile %}
<div class="user__orders">
    <p class="title1">Мої замовлення</p>
    <ul class="orders">
        <li class="heading_wrapper">
            <div class="heading main">
                <p>Статус замовлення</p>
                <p>Тип доставки</p>
                <p>Сума</p>
                <p class="date">Час замовлення</p>
            </div>
           
            {% for order in orders %}
                <li class="order">
                    <div class="heading">
                        <p>{{ order.status }}</p>
                        <p>{{ order.pay_type }}</p>
                        <p>{{ order.total }} грн</p>
                        <p class="date">{{ order.created }}</p>
                    </div>
                    
                    <ul class="products">
                        <p class="bold title">Товари на замовлення</p>
                        {% for product in order.products %}
                            <li class="product">
                                <div class="image">
                                    <a href="{{ product.url }}">
                                        <img src="{{ product.variant.images.0.s }}" alt="">
                                    </a>
                                </div>
                                <div class="info">
                                    <a href="{{ product.variant.brand_url }}" class="brand">{{ product.variant.brand }}</a>
                                    <p class="name">{{ product.variant.name }}</p>
                                    <p class="quantity">{{ product.quantity }} шт. x {{ product.price }} грн.</p>
                                </div>
                                <p class="total">{{ product.total }} грн.</p>
                            </li>
                        {% endfor %}
                        <div>
                            <a class="button" href="{% url 'order:repeat' id=order.id %}">Повторити</a>
                        </div>
                        
                    </ul>
                </li>
            {% endfor %}
    </ul>
    
</div>
{% endblock %}

templates/user/profile/profile__passwordchange.html
{% extends './profile.html' %}
{% load static %}
{% block profile %}
<div class="forms user_password_change">
    <p class="title1">Зміна паролю</p>

    {% if done %}
        <p>Пароль змінено</p>
    {% else %}
        <ul>
            <li>
                <form class="form" action="" method="POST">
                    {% csrf_token %}
                    <div class="fields">
                        {% for field in form %}
                            <div class="{{ field.name }}">
                                {{ field.label_tag }}
                                {{ field.errors }}
                                <p>{{ field }}</p>
                            </div>
                        {% endfor %}
                    </div>
                    
                    <button type="submit">Змінити пароль</button>
                </form>
            </li>
        </ul>
    {% endif %}
    
</div>
{% endblock %}

templates/user/profile/profile__questions.html
{% extends './profile.html' %}
{% load static %}

{% block profile %}
<div class="user__comments reviews">
    <p class="title1">Мої запитання</p>
    <ul class="product_reviews">
        {% include 'shop/product/comments/comments__list.html' with comment_product=True %}
    </ul>
</div>
{% endblock %}

templates/user/profile/profile__subscribe.html
{% extends './profile.html' %}
{% load static %}
{% block profile %}
<div class="user__subscribe">
    <p class="title1">Передплати на розсилку</p>
   
    <form class="form" action="{% url 'user:user_subscribe' %}" method="POST">
        {% csrf_token %}
        {{ formset.management_form }}
        {% for form in formset %}
            <div class="hidden">
                {% for field in form.hidden_fields %}
                    {{ field }}
                {% endfor %}
            </div>
            <div class="list">
                {% for field in form.visible_fields %}
                    {{ field }}
                {% endfor %}
            </div>
        {% endfor %}
        <button type="submit">Обновити</button>
    </form>
   
</div>
{% endblock %}

templates/user/profile/profile__wishlist.html
{% extends './profile.html' %}
{% load static %}
{% block profile %}
<div class="user__wishlist">
    <p class="title1">Список бажань</p>
    <ul class="wishlist__products"></ul>
</div>
{% endblock %}