apps/blog/urls.py
from django.urls import path
from apps.blog import views


app_name = 'blog'


urlpatterns = [
   path('',        views.BlogViewSet.as_view({'get': 'list'}), name="list"),
   path('<slug>/', views.BlogViewSet.as_view({'get': 'get'}),  name="post"),
]

apps/core/urls.py
from django.db.models import signals
from django.urls import include, path, re_path
from apps.core import views


app_name = 'core'

urlpatterns = [
    path('sitemap.xml', views.sitemap, name='sitemap'),
    path('recall',      views.recall,  name='recall'),
    path('set_language/<language>/', views.set_language, name="set_language")
]

apps/opt/urls.py
from django.urls import include, path, re_path

from apps.opt import views
from django.views.generic import TemplateView

app_name = 'opt'

urlpatterns = [
    path('',               views.WhoosaleView.as_view(), name='opt'),
    path('success/',       TemplateView.as_view(template_name="opt/success.html"), name='success'),
    path('offer/',         TemplateView.as_view(template_name="opt/salons/main.html"), name='opt_offer'),
    path('offer/quiz/',    views.SalonsView.as_view(),   name='opt_offer_quiz'),
    # path('get_analitics/', views.get_analitics, name='get_analitics'),
]

apps/shop/urls.py
from django.urls import include, path, re_path
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView
from django.views.decorators.vary import vary_on_headers

from django.views.generic import TemplateView
from apps.shop import views


app_name = 'shop'

comments = [
    path('product-<int:product_id>/comment_form/',                       views.ProductViewSet.as_view({'get' : 'comment_form', 'post' : 'comment_form'}), name="product_comment_form"),
    path('product-<int:product_id>-<comment_type>/comment_form/',        views.ProductViewSet.as_view({'get' : 'comment_form', 'post' : 'comment_form'}), name="product_comment_form"),
    path('comment-<int:comment_id>/reply_form/',                         views.ProductViewSet.as_view({'get' : 'reply_form',   'post' : 'reply_form'}),   name="comment_reply_form"),
    path('comment-<int:comment_id>/reply_form/parent-<int:parent_id>',   views.ProductViewSet.as_view({'get' : 'reply_form',   'post' : 'reply_form'}),   name="comment_reply_form"),
]


product = [
    path('comments/', include(comments)),
    path('serie/product-<int:product_id>', views.ProductViewSet.as_view({'get' : 'fetch_serie'}), name="fetch_serie"),
    re_path(
        r'''^catalogue/(?P<category>([/\w-]*))/'''
        r'''(?P<brand>[\w-]+)__'''
        r'''(?P<product_slug>([\w-]+))'''
        r'''_(?P<product_id>[\d+]+)/?$''',
        views.ProductViewSet.as_view({'get' : 'get', 'post' : 'post'}) , 
        name='product'
    ),
    re_path(
        r'''^catalogue/(?P<category>([/\w-]*))/'''
        r'''(?P<brand>[\w-]+)__'''
        r'''(?P<product_slug>([\w-]+))'''
        r'''_(?P<product_id>[\d+]+)'''
        r'''?(?:-(?P<variant_id>[\d+]+))?/?$''', 
        views.ProductViewSet.as_view({'get' : 'get', 'post' : 'post'}) , 
        name='variant'
    ),
    
]


catalogue = [
    path('brands/', views.brands, name="brands_all"),
    re_path(
        r'''^brands/(?P<brand>[\w-]+)?/?'''
        r'''(?:\/(?P<category>([\w-]*)))?/?'''
        r'''(?:\/page=(?P<page>[\d+]+))?/?'''
        r'''(?:\/price=(?P<price>[,\w-]+))?/?'''
        r'''(?:\/sort=(?P<sort>price_asc|price_dsc|newest|popular))?/?'''
        r'''(?:\/(?P<atributes>([\w-]+(=[,\w-]*))?(((\/[\w-]+(=[,\w-]*))?)*)))?/$''',
        views.BrandsCatalogue.as_view(), 
        name="brands"
    ),
    path('catalogue/', views.Catalogue.as_view(),  name="catalogue"),
    re_path(
        r'''^catalogue/'''
        r'''?(?:\/(?P<category>([/\w-]*)))?/'''
        r'''?(?:discount=(?P<discount>yes|no))?/'''
        r'''?(?:\/brand=(?P<brand>[,\w-]+))?/'''
        r'''?(?:\/page=(?P<page>[\d+]+))?/'''
        r'''?(?:\/price=(?P<price>[,\w-]+))?/'''
        r'''?(?:\/sort=(?P<sort>price_asc|price_dsc|newest|popular))?/'''
        r'''?(?:\/(?P<atributes>([\w-]+(=[,\w-]*))?(((\/[\w-]+(=[,\w-]*))?)*)))?/''',
        views.Catalogue.as_view(), 
        name="catalogue"
    ),

   
]


cart = [
    path('add/',    views.CartViewSet.as_view({'post' : 'add'}),    name='cart__add'),
    path('delete/', views.CartViewSet.as_view({'post' : 'delete'}), name='cart__delete'),
    path('get/',    views.CartViewSet.as_view({'get' : 'get'}),     name='cart__get'),
    path('clear/',  views.CartViewSet.as_view({'get' : 'clear'}),   name='cart__clear'),
]


templates = [
    path('buyer-info', views.TemplatesView.as_view({'get' : 'buyer_info'}), name='tpl-buyer_info')
]


urlpatterns = [
    path('',             views.home, name='home'),
    path('watchlist',    views.WatchListView.as_view({'get': 'get'}), name="watchlist"),
    path('cart/',        include(cart)),
    path('feed.xml',        views.FeedView.as_view(), name="feed"),
    path('templates',    include(templates)),
    path('', include(product)),
    path('', include(catalogue)),
    path('appear__product',      views.appear__product,  name='appear__product'),
    

]

project/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, re_path
from django.conf.urls.i18n import i18n_patterns
from django.urls import reverse
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve


urlpatterns = []

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()
  


urlpatterns += i18n_patterns(
    path('',          include('apps.user.urls',      namespace='user')),
    path('blog/',     include('apps.blog.urls',      namespace='blog')),
    path('order/',    include('apps.order.urls',     namespace='order')),
    path('core/',     include('apps.core.urls',      namespace='core')),
    path('search/',   include('apps.search.urls',    namespace='search')),
    path('wishlist/', include('apps.wishlist.urls',  namespace='wishlist')),
    path('opt/',      include('apps.opt.urls',       namespace='opt')),
    path('i18n/',     include('django.conf.urls.i18n')),
    path('admin/clearcache/', include('clearcache.urls')),
    path('admin/',  admin.site.urls),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    
    # path('jet/',    include('jet.urls', 'jet')),
    # path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('1c/',     include('apps.sync1c.urls',  namespace='sync1c')),
    path('',        include('apps.shop.urls',   namespace='shop')),
    path('',        include('apps.pages.urls',  namespace='pages')),
    prefix_default_language=False
)

templates/base/footer/footer.html
{% load static %}{% load i18n %}{% load compress %}{% load cache %}{% get_current_language as LANGUAGE_CODE %}
<footer>
    <div class="content">
        <div class="contacts">
            <div class="block">
                
                <span class="title">Контакти</span>
                <span>
                    <span>Email:</span>
                    <a href="mailto:office.fortisbeauty@gmail.com">office.fortisbeauty@gmail.com</a>
                    <!-- <a href="mailto:{{ page.email }}">{{ maindata.email }}</a> -->
                </span>
            </div>
            
            <ul class="phones">
                {% for phone in phones %}
                    <li>
                        <span>{{ phone.name }}</span><br>
                        <a href="tel:{{ phone.phone_nums }}">{{ phone.phone }}</a>
                    </li>
                {% endfor %}
            </ul>
            <span>Пн-пт 10:00-19:00</span>
        </div>
        <div class="links">
            <div class="info">
                <span class="title">Інформація</span>
                <ul>
                    <li>
                        <a href="{% url 'shop:catalogue' %}">Каталог</a>
                    </li>
                    <li>
                        <a href="{% url 'shop:brands_all' %}">Бренди</a>
                    </li>
                    <li>
                        <a href="{% url 'pages:about' %}">Про нас</a>
                    </li>
                    <li>
                        <a href="{% url 'blog:list' %}">Блог</a>
                    </li>
                    <li>
                        <a href="{% url 'pages:contacts' %}">Контакти</a>
                    </li>
                </ul>
            </div>
            
            <div class="block partners">
                <span class="title">Партнерам</span>
                <ul>
                    <li>
                        <a href="{% url 'opt:opt' %}">Співпраця</a>
                    </li>
                </ul>
            </div>
            <div class="block clients">
                <span class="title">Клієнтам</span>
                <ul>
                    <li>
                        <a href="{% url 'pages:delivery' %}">Доставка</a>
                    </li>
                    <li>
                        <a href="{% url 'pages:payment' %}">Оплата</a>
                    </li>
                    <li>
                        <a href="{% url 'pages:terms_of_use' %}">Умови використання</a>
                    </li>

                    
                </ul>
            </div>
        </div>
    
        <div class="payment">
            <div class="block payment">
                <span class="title">Спосіб оплати</span>
                <ul class="pay_methods">
                    <li>
                        <img src="{% static 'img/paymethods.png' %}" alt="paymethods">
                    </li>
                </ul>
            </div>
            <div class="block payment">
                <span class="title">Соціальні мережі</span>
                <ul class="socials">
                    <li>
                        <a href="https://www.instagram.com/fortisbeauty.ua/">
                            <img src="{% static 'img/instagram.png' %}" alt="instagram">
                        </a>
                    </li>
                    <li>
                        <a href="https://www.facebook.com/fortisbeauty.store/">
                            <img src="{% static 'img/facebook.png' %}" alt="facebook">
                        </a>
                    </li>
                </ul>
            </div>
            
                
            <!-- <a href="{% url 'core:sitemap' %}">{% trans 'Карта сайта' %}</a> -->
        </div>
    </div>
    


    
    
</footer>