apps/user/urls.py
from django.urls import path, re_path, include
from django.contrib.auth import views as authViews
from django.views.generic import TemplateView
from apps.user.forms import PasswordRestoreForm
from . import views

app_name = 'user'


profile = [
    path('',                 views.user_data,            name='profile'),
    path('orders/',          views.user_orders,          name='user_orders'),
    path('wishlist/',        views.user_wishlist,        name='user_wishlist'),
    path('company/',         views.user_company,         name='user_company'),
    path('comments/',        views.user_comments,        name='user_comments'),
    path('questions/',       views.user_questions,       name='user_questions'),
    path('logout/',          views.user_logout,          name='user_logout'),
    path('password_change/', views.user_password_change, name='user_password_change'),
    
]


registration = [
    path('',                   views.CustomerRegistration.as_view(), name='registration'),
    path('business/',          views.PartnerRegistration.as_view(),  name='registration_business'),
    path('success/',           TemplateView.as_view(template_name="user/registration/customer/success.html"), name='registration_success'),
    path('business/success/',  TemplateView.as_view(template_name="user/registration/partner/success.html"),  name='registration_business_success'),
]


pssword_restore = [
    path(
        'html/', TemplateView.as_view(
            template_name = 'user/password_restore/email_template.html',
        ), 
        kwargs={'uidb64' : '123123', 'token' : '1232'},
        name='restore_password__success',
    ),
   
    path(
        '',                        
        authViews.PasswordResetView.as_view(
            form_class =    PasswordRestoreForm,
            template_name = 'user/password_restore/form.html',
            from_email =    'office.fortisbeauty@gmail.com',
            success_url =   '/restore_password/success/',
        ), 
        name='restore_password'
    ),
    path(
        'success/',                
        TemplateView.as_view(
            template_name = 'user/password_restore/success.html'
        ), 
        name='restore_password__success'
    ),
    path(
        'done/', 
        authViews.PasswordResetDoneView.as_view(), 
        kwargs={'template_name': 'user/password_restore/done.html'}, 
        name='restore_password__done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        authViews.PasswordResetConfirmView.as_view(
            template_name = 'user/password_restore/link_form.html',
            success_url =   '/login',
        ),
        name='restore_password__confirm'
    ),
]


urlpatterns = [
    path('login/',   views.LoginView.as_view(),  name='login'),
    path('logout/',  views.user_logout,          name='logout'),
    path('profile/',           include(profile)),
    path('restore_password/',  include(pssword_restore)),
    path('registration/',      include(registration)),
    path('activate/<uidb64>/<token>/',views.activate, name='activate'),  
]

apps/wishlist/urls.py
from django.urls import path
from apps.wishlist import views


app_name = 'wishlist'


urlpatterns = [
    path('',                 views.WishlistDataView.as_view(),              name='wishlist'),
    path('add/<int:id>/',    views.WishlistView.as_view({'get': 'put'}),    name='wishlist-add'),
    path('delete/<int:id>/', views.WishlistView.as_view({'get': 'delete'}), name='wishlist-delete'),
]

project/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, re_path
from django.conf.urls.i18n import i18n_patterns
from django.urls import reverse
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve


urlpatterns = []

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()
  


urlpatterns += i18n_patterns(
    path('',          include('apps.user.urls',      namespace='user')),
    path('blog/',     include('apps.blog.urls',      namespace='blog')),
    path('order/',    include('apps.order.urls',     namespace='order')),
    path('core/',     include('apps.core.urls',      namespace='core')),
    path('search/',   include('apps.search.urls',    namespace='search')),
    path('wishlist/', include('apps.wishlist.urls',  namespace='wishlist')),
    path('opt/',      include('apps.opt.urls',       namespace='opt')),
    path('i18n/',     include('django.conf.urls.i18n')),
    path('admin/clearcache/', include('clearcache.urls')),
    path('admin/',  admin.site.urls),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    
    # path('jet/',    include('jet.urls', 'jet')),
    # path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('1c/',     include('apps.sync1c.urls',  namespace='sync1c')),
    path('',        include('apps.shop.urls',   namespace='shop')),
    path('',        include('apps.pages.urls',  namespace='pages')),
    prefix_default_language=False
)

apps/wishlist/models.py
from django.db import models
from django.utils.translation import ugettext, ugettext_lazy as _
from django.utils.timezone import now



class Wishlist(models.Model):
    user =    models.ForeignKey('user.CustomUser', on_delete=models.CASCADE, verbose_name=_("Пользователь"), related_name='products')
    variant = models.ForeignKey('shop.Variant',    on_delete=models.CASCADE, verbose_name=_("Товар"))
    date =    models.DateTimeField(default=now)

    class Meta:
        ordering = ['-date']
        unique_together = [['user', 'variant']]

    def __str__(self):
        return ''

    def save(self):
        self.date = now()
        super(Wishlist, self).save()

apps/wishlist/views.py
from django.shortcuts import render
from django.template.loader import render_to_string
from rest_framework import viewsets
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated, AllowAny
from rest_framework.response import Response
from apps.wishlist.models import Wishlist
from apps.wishlist.serializers import WishlistSerializer
from apps.shop.models import Variant




def get_wishlist_data(request):
    user = request.user
    is_whoosaler = user.is_whoosaler if user.is_authenticated else None
    if user.is_authenticated:
        wishlist = Wishlist.objects.filter(user=request.user)
    else:
        wishlist = Wishlist.objects.none()
    wishlist_serialized = WishlistSerializer(wishlist, context={'is_whoosaler': is_whoosaler},  many=True).data
    return {
        'html' : render_to_string('wishlist/wishlist__list.html', {
            'wishlist' : wishlist_serialized, 'request' : request
        }),
        'total' : wishlist.count()
    }




class WishlistDataView(APIView):
    permission_classes = [AllowAny]

    def get(self, request):
        return Response({'wishlist' : get_wishlist_data(request)})




class WishlistView(viewsets.ViewSet):
    permission_classes = [IsAuthenticated]

    def put(self, request, id):
        user = request.user
        variant = Variant.objects.get(id=id)
        try:
            wish = Wishlist.objects.get(user=user, variant=variant)
        except:
            wish = Wishlist(user=user, variant=variant)
        wish.save()
        return Response({'wishlist' : get_wishlist_data(request)})
    

    def delete(self, request, id):
        user = request.user
        variant = Variant.objects.get(id=id)
        try:
            wish = Wishlist.objects.get(user=request.user, variant=variant)
            wish.delete()
        except:
            pass
        return Response({'wishlist' : get_wishlist_data(request)})

templates/wishlist/sidebar__wishlist.html
{% load static %}
{% load i18n %}
<!-- LINKS -->
{% block links %}
    <link rel="stylesheet" href="{% static 'css/shop/wishlist.css' %}">
{% endblock %}

<div class="sidebar wishlist right" id="sidebar_wishlist">
    <!-- TITLE -->
    <div class="title">
        <p class="h3 pl32">{% trans 'Список бажань' %} ❤️</p>
        <img class="close" onclick="SidebarClose('sidebar_wishlist')" src="{% static 'img/icons/close.png' %}" alt="X" >
    </div>
    <!-- MAIN -->
    <div class="main" id="sidebar__wishlist__products__list">
        {% include './wishlist__list.html' %}
    </div>
    <!-- ACTIONS -->
    <div class="actions"></div>
</div>
<div class="sidebar-outer" id="sidebar_wishlist_outer" data-id="sidebar_wishlist"></div>

templates/wishlist/wishlist.html
{% load static %}<div class="sidebar wishlist right" id="sidebar_wishlist">
    <div class="title">
        <span class="h4">Список бажань</span>
        <img class="close" onclick="SidebarClose('sidebar_wishlist')" src="{% static 'img/icons/close.png' %}" alt="X" >
    </div>
    <div class="main">
        <ul class="wishlist__products"></ul>
    </div>
</div>
<div class="sidebar-outer" id="sidebar_outer" data-id="sidebar_cart"></div>

templates/wishlist/wishlist__list.html
{% load static %}{% load i18n %}{% if request.user.is_authenticated %}
{% if wishlist|length > 0 %}
        {% for item in wishlist %}
            <li class="wishlist__product">
                <a class="image__wrapper" href="{{ item.variant.url }}">
                    <span class="image">
                        <img class="product_image" src="{% if item.variant.image %}{{ item.variant.image }}{% else %}{% static 'img/no_image.png' %}{% endif %}" alt="img">
                    </span> 
                </a>
                <div class="info">
                    <a href="{{ item.variant.url }}" class="name">{{ item.variant.name }}</a>
                    <span class="price">
                        <span>{{ item.variant.price }} грн.</span>
                        <button class="buy" data-id="{{ item.variant.id }}" onclick="WishlistToCart(this)">Купити</button>
                    </span>
                    <img class="remove" onclick="RemoveFromWishlist('{{ item.variant.id }}')" src="{% static 'img/icons/svg/Garbage.svg' %}" alt="remove">
                </div>    
            </li>
        {% endfor %}
    {% else %}
        <li>{% trans 'Список бажань поки що порожній. Додати щось)' %}</li>
    {% endif %}
{% else %}
    <li class="center">
        <span class="h5">
            {% trans 'Додавати товари до списку бажань можуть лише зареєстровані користувачі.' %}
        </span>    
        <a class="button" href="{% url 'user:registration' %}">
        {% trans 'Реєстрація' %}  
        </a>
    </li>
{% endif %}